FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o frontend-sse ./cmd/frontend-sse/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/frontend-sse .
EXPOSE 8082
CMD ["./frontend-sse"]