FROM golang:1.25-alpine AS builder
WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source and build
COPY . .
RUN go build -o ingestion ./cmd/ingestion/main.go

# Final lightweight stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/ingestion .
EXPOSE 8081
CMD ["./ingestion"]